# For a Github action version of Travis CI. This will check code over all supported versions
# Travis CI will cover multi-os

name: Python check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9.0-rc.1', '3.9.0-beta.5', '3.9.0-beta.4', '3.8.5', '3.8.4', '3.8.3', '3.8.2', '3.8.1', '3.8.0']
    steps:
      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install -r dev-requirements.txt
          sudo apt-get install libxml2-dev libxslt-dev python-dev
          sudo apt-get build-dep python3-lxml
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        run: |
          make test || pytest tests/ -vvv --durations=3

      - name: Lint with flake8
#         # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
#         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --show-source --statistics --max-complexity=20

